title: A github pages site with jekyll
author: PuneetGopinath
email: baalkrshna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A example github pages site with jekyll

# social links
twitter_username: PuneetGopinath # DO NOT include the @ character, or else the build will fail!
github_username:  PuneetGopinath # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
